Ext.define('admin.store.indexMenuTreeStore',{
    extend:'Ext.data.TreeStore',
    defaultRootId:'root',
    model:'admin.model.indexMenuTreeModel',
    proxy:{
        type:'ajax',
        autoLoad:true,
        url:'./server/data.json',
        reader:'json'
    }
});
